- peripherals/proxy/nginx.conf
Solves the 502 observed on mainnet
> Enable keep alive to read and test endpoint.

- peripherals/proxy/nginx.conf
Brings fixes of #513 to main. Close #512.
> [0.4 -> main] Enable keep alive to read and test endpoint

- contract/include/evm_runtime/evm_contract.hpp
- contract/src/actions.cpp
- contract/tests/native_token_tests.cpp
> Reject non eos token in bridging

- contract/tests/native_token_tests.cpp
> add some additional tests for invalid addresses in EOS->EVM bridge memos

- contract/tests/contracts/solidity/Distributor.sol
- contract/tests/contracts/solidity/RevertTest.sol
- contract/tests/native_token_tests.cpp
Resolves #409 
Co-Authored-By: Matt Witherspoon <32485495+spoonincode@users.noreply.github.com>
> more briging tests

- silkrpc/commands/eth_api.cpp
- silkrpc/core/estimate_gas_oracle.cpp
> eth_call: use default from address when not specified

- silkrpc/core/estimate_gas_oracle.cpp
> Fix gas estimation return value

- contract/src/actions.cpp
> Return error number and more descriptive message when validation failed

- silkrpc/core/evm_executor.cpp
> [0.5] Handle transfers from reserved address in the same way as other places

- docs/compilation_and_testing_guide.md
- docs/local_testnet_deployment_plan.md
- docs/public_testnet_deployment_plan.md
- peripherals/tx_wrapper/README.md
Resolve #560 
Resolve #528 
Resolve #565
> Fix documentation

- .github/workflows/build-contract-test.sh
- .github/workflows/build-contract.sh
Resolves: https://github.com/eosnetworkfoundation/eos-evm/issues/632
> Reduce artifact size remove obj

- src/actions.cpp
> [0.6] Allow transfer non-EOS tokens out.

- src/actions.cpp
> [0.6->main] Allow transfer non-EOS tokens out

- include/evm_runtime/types.hpp
- src/config_wrapper.cpp
- src/utils.cpp
> [1.0 -> main] Check ingress fee precision

- tests/version_tests.cpp
> [1.0] Update silkworm 1.0.2

- tests/version_tests.cpp
Reverts eosnetworkfoundation/eos-evm-contract#740
> Revert "[1.0] Update silkworm 1.0.2"

- include/evm_runtime/types.hpp
- src/CMakeLists.txt
- src/config_wrapper.cpp
- src/utils.cpp
- tests/version_tests.cpp
> [1.0 -> main] Update silkworm 1.0.2

- src/CMakeLists.txt
> [1.0] Bump 1.0.0-rc4 version

- src/CMakeLists.txt
> [1.0 -> main] Bump 1.0.0-rc4 version

- .github/workflows/contract.yml
Will fix the integrate tests in node repo after we merge the fix into main branch.
> [1.0] fix ci by using new upload script.

- .github/workflows/contract.yml
> [1.0->main] Use upload-artifact v4 script in CI

- src/CMakeLists.txt
> [1.0 -> main] Bump 1.0.0 version

- include/evm_runtime/config_wrapper.hpp
- src/config_wrapper.cpp
- tests/gas_fee_tests.cpp
- tests/gas_param_tests.cpp
> [1.0] Remove 1gwei limit when setting gas price

- include/evm_runtime/config_wrapper.hpp
- src/config_wrapper.cpp
- tests/gas_fee_tests.cpp
- tests/gas_param_tests.cpp
> [1.0->main] merge changes removing the 1gwei gas price limit

- .github/workflows/contract.yml
- tests/basic_evm_tester.hpp
Builds on #773 to update for Spring `main`.
> Update for Spring main 1.1.0

- .github/workflows/contract.yml
- docs/local_testnet_deployment_plan.md
> fix cicd, update local_testnet_deployment_plan.md

- tests/gas_fee_tests.cpp
> [1.0] add testcase for ingress gas limit

- tests/gas_fee_tests.cpp
> [1.0->main] forward ingress gas limit test

- tests/basic_evm_tester.hpp
> [1.0] Fix tests broken by spring 1.1

- README.md
> [2.0] Update README.md

- README.md
> [2.0->main] update readme

- include/evm_runtime/evm_contract.hpp
- include/evm_runtime/runtime_config.hpp
- src/actions.cpp
- tests/basic_evm_tester.cpp
- tests/basic_evm_tester.hpp
- tests/call_tests.cpp
> [1.2] backport gas payer feature from release/2.0

- src/CMakeLists.txt
> [1.2] bump version 1.2.0

- src/CMakeLists.txt
> [1.1] version bump 1.1.1

- src/actions.cpp
- tests/exec_tests.cpp
> [1.2->2.0] forward callback fix

- src/actions.cpp
- tests/exec_tests.cpp
> [2.0->main] fix callback
